// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

import CanonicalSumEmission
import Foundation
import SwiftParser
import SwiftSyntax

/// The codegen vehicle of the Swift ceremony killer, and the scaffold's
/// default: emits canonical `{"case": …}` coders for every enum that declares
/// `CanonicalSumCodable` (the Duet kernel's marker protocol) in a source file.
/// The conformance at the declaration IS the annotation — compiler-checked,
/// autocompleted; the generated extension provides the witnesses plus the
/// `canonicalCodersGenerated` sentinel (it defeats SE-0295 silent synthesis, so
/// a missing generated file fails compilation AT the enum declaration). One
/// generated file per source file (`XFeature.swift` → `XSerialization.generated.swift`,
/// committed build products; regen rides `duet record`, drift rides
/// `duet record --check`). Emission comes from `CanonicalSumEmission` — the one
/// rule-set the `@CanonicalSum` macro opt-in shares.
public enum CanonicalSumGen {
  public struct Output {
    public let sourceURL: URL
    public let outputURL: URL
    public let content: String
    public let enumCount: Int
  }

  /// Every non-generated .swift file under `sourcesRoot` that mentions the marker
  /// protocol — the zero-config scan set (`Sources/**` of the manifest-derived
  /// package; cheap substring prefilter, then a real parse).
  public static func scan(sourcesRoot: URL) -> [URL] {
    guard
      let enumerator = FileManager.default.enumerator(
        at: sourcesRoot, includingPropertiesForKeys: nil)
    else { return [] }
    var hits: [URL] = []
    for case let url as URL in enumerator {
      let name = url.lastPathComponent
      guard name.hasSuffix(".swift"), !name.hasSuffix(".generated.swift") else { continue }
      guard let source = try? String(contentsOf: url, encoding: .utf8) else { continue }
      if source.contains("CanonicalSumCodable") { hits.append(url) }
    }
    return hits.sorted { $0.path < $1.path }
  }

  /// Parses one source file and assembles its generated-coders file. Returns nil
  /// when the file declares no `CanonicalSumCodable` enum (nothing to generate —
  /// e.g. the marker only appears in a comment or the protocol's own declaration).
  public static func generate(fromSource sourceURL: URL) throws -> Output? {
    let source = try String(contentsOf: sourceURL, encoding: .utf8)
    let collector = Collector(viewMode: .sourceAccurate)
    collector.walk(Parser.parse(source: source))
    guard !collector.enums.isEmpty else { return nil }

    let stem = sourceURL.deletingPathExtension().lastPathComponent
      .replacingOccurrences(of: "Feature", with: "")
    let outputURL = sourceURL.deletingLastPathComponent()
      .appendingPathComponent("\(stem)Serialization.generated.swift")

    var out: [String] = [
      "// Copyright (c) 2026 Modaal.dev",
      "// Licensed under the MIT License. See LICENSE file for details.",
      "",
      "// GENERATED by `duet canonical-sum` from \(sourceURL.lastPathComponent) — do not edit.",
      "// Regenerate: `duet record` (regen is folded in) or `duet canonical-sum`;",
      "// drift-gated by `duet record --check`. Canonical `{\"case\": …}` coding per the",
      "// framework's serialization contract (contracts/serialization.md §4).",
      "",
    ]
    var imports = Set(collector.imports)
    imports.insert("Foundation")
    for name in imports.sorted() { out.append("import \(name)") }
    out.append("")
    out.append(contentsOf: CanonicalSumEmission.codingKeyDecls(indent: ""))

    for sumEnum in collector.enums {
      out.append("")
      // The conformance is declared at the enum (the annotation); this extension
      // supplies the witnesses. The sentinel defeats SE-0295 synthesis-on-absence.
      out.append("extension \(sumEnum.name) {")
      out.append("  public static let canonicalCodersGenerated = true")
      out.append("")
      out.append(
        contentsOf: CanonicalSumEmission.initDecl(enumName: sumEnum.name, cases: sumEnum.cases))
      out.append("")
      out.append(contentsOf: CanonicalSumEmission.encodeDecl(cases: sumEnum.cases))
      out.append("}")
    }
    out.append("")
    return Output(
      sourceURL: sourceURL, outputURL: outputURL,
      content: out.joined(separator: "\n"), enumCount: collector.enums.count)
  }

  // MARK: - Collection (this vehicle's half; the macro walks its own nodes)

  struct SumEnum {
    let name: String
    let cases: [SumCase]
  }

  final class Collector: SyntaxVisitor {
    var imports: [String] = []
    var enums: [SumEnum] = []

    override func visit(_ node: ImportDeclSyntax) -> SyntaxVisitorContinueKind {
      imports.append(node.path.description.trimmingCharacters(in: .whitespaces))
      return .skipChildren
    }

    override func visit(_ node: EnumDeclSyntax) -> SyntaxVisitorContinueKind {
      let conformances = node.inheritanceClause?.inheritedTypes.map {
        $0.type.trimmed.description
      }
      guard conformances?.contains("CanonicalSumCodable") == true else {
        return .skipChildren
      }
      var cases: [SumCase] = []
      for member in node.memberBlock.members {
        guard let caseDecl = member.decl.as(EnumCaseDeclSyntax.self) else { continue }
        for element in caseDecl.elements {
          var fields: [SumCase.Field] = []
          for parameter in element.parameterClause?.parameters ?? [] {
            let rawLabel = parameter.firstName?.text
            let label = rawLabel == "_" ? nil : rawLabel
            let type = parameter.type.description.trimmingCharacters(in: .whitespaces)
            fields.append(
              SumCase.Field(label: label, type: type, optional: type.hasSuffix("?")))
          }
          cases.append(SumCase(name: element.name.text, fields: fields))
        }
      }
      enums.append(SumEnum(name: node.name.text, cases: cases))
      return .skipChildren
    }
  }
}
