// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

import Foundation

/// One committed build product `duet design-tokens` writes.
struct GeneratedDesignTokenFile {
  /// Repo-relative path.
  var path: String
  var content: String
}

/// The emitters — one config in, both languages' vocabulary and value files out.
///
/// What is generated is exactly the two layers that have a twin on the other
/// platform: the vocabulary (the case lists) and the palette (the values). The
/// role bindings, the resolvers that turn a family token into a platform face,
/// and the theme registration stay hand-authored, because Material slots and
/// Apple roles are different sets and a resolver reads app-owned font
/// resources.
enum DesignTokensEmitter {
  /// Column the prose comments wrap at, header indentation included.
  static let wrapColumn = 80

  static func emit(config: DesignTokenConfig) -> [GeneratedDesignTokenFile] {
    var files: [GeneratedDesignTokenFile] = []
    if let target = config.swift { files += emitSwift(config: config, target: target) }
    if let target = config.kotlin { files += emitKotlin(config: config, target: target) }
    return files
  }

  /// Every path this config's targets own — the set `--check` compares the
  /// output directories against, so a vocabulary dropped from the config is
  /// reported instead of left behind compiling.
  static func ownedPaths(config: DesignTokenConfig) -> Set<String> {
    var paths: Set<String> = []
    if let target = config.swift {
      let root = target.output
      paths.formUnion(["SemanticColor.swift", "SemanticFont.swift", "SemanticGradient.swift",
                       "\(target.theme)Palette.swift"].map { "\(root)/\($0)" })
    }
    if let target = config.kotlin {
      let root = target.output
      paths.formUnion(["SemanticColor.kt", "SemanticFont.kt", "SemanticGradient.kt",
                       "\(target.palette).kt"].map { "\(root)/\($0)" })
    }
    return paths
  }

  // MARK: - Shared rendering

  /// Wraps a paragraph run to `wrapColumn`, each line carrying `prefix`.
  /// Paragraphs are separated in the source by a blank line and stay separated.
  static func comment(_ text: String, prefix: String, indent: String) -> [String] {
    let limit = max(24, wrapColumn - indent.count - prefix.count)
    var out: [String] = []
    // Prose is authored as a folded scalar (`>-`), which renders each blank
    // line in the config as a single newline — so one newline is a paragraph.
    let paragraphs = text.components(separatedBy: "\n").filter { !$0.isEmpty }
    for (index, paragraph) in paragraphs.enumerated() {
      if index > 0 {
        // The blank line between paragraphs keeps the marker and drops the
        // trailing space, so no generated file carries trailing whitespace.
        var marker = prefix
        while marker.hasSuffix(" ") { marker.removeLast() }
        out.append("\(indent)\(marker)")
      }
      var line = ""
      for word in paragraph.split(whereSeparator: \.isWhitespace) {
        if line.isEmpty {
          line = String(word)
        } else if line.count + 1 + word.count <= limit {
          line += " " + word
        } else {
          out.append("\(indent)\(prefix)\(line)")
          line = String(word)
        }
      }
      if !line.isEmpty { out.append("\(indent)\(prefix)\(line)") }
    }
    return out
  }

  /// `34` for a whole number, `-0.01` otherwise — the CGFloat literal form.
  static func swiftNumber(_ value: Double) -> String {
    value == value.rounded() ? String(Int(value)) : String(value)
  }

  /// `34.0` for a whole number, `-0.01` otherwise — the Double literal form.
  static func kotlinNumber(_ value: Double) -> String {
    value == value.rounded() ? String(format: "%.1f", value) : String(value)
  }

  static func hex6(_ value: UInt32) -> String {
    String(format: "0x%06X", value)
  }

  static func hex8(_ value: UInt32) -> String {
    String(format: "0x%08X", value)
  }

  /// Joins the emitted lines, collapsing any run of blank lines to one — a
  /// heading followed by a documented token would otherwise open with two.
  static func render(_ lines: [String]) -> String {
    var out: [String] = []
    for line in lines where !(line.isEmpty && out.last?.isEmpty == true) {
      out.append(line)
    }
    return out.joined(separator: "\n")
  }

  static func header(_ lines: [String]) -> [String] {
    ["// Copyright (c) 2026 Modaal.dev",
     "// Licensed under the MIT License. See LICENSE file for details.",
     ""] + lines + [""]
  }

  static let generatedBanner = [
    "// GENERATED by `duet design-tokens` from \(DesignTokenConfig.relativePath) —",
    "// do not edit. Change a value in the config and regenerate:",
    "// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,",
    "// which regenerates in memory and compares.",
  ]

  // MARK: - Swift

  static func emitSwift(config: DesignTokenConfig, target: DesignTokenConfig.SwiftTarget)
    -> [GeneratedDesignTokenFile]
  {
    var files: [GeneratedDesignTokenFile] = [
      .init(path: "\(target.output)/SemanticColor.swift",
            content: swiftVocabulary(
              enumName: "SemanticColor", conformance: "ColorAssetable", engine: target.engine,
              doc: """
                The app's colour vocabulary — the one list, read by this tree and by \
                every other tree generated from the same config.

                A token is chosen by what it means, never by what it looks like: the \
                value behind it is the config's to change.
                """,
              groups: config.colors.map { (name: $0.name, tokens: $0.tokens.map { ($0.name, $0.doc) }) })),
      .init(path: "\(target.output)/SemanticFont.swift",
            content: swiftVocabulary(
              enumName: "SemanticFont", conformance: "FontAssetable", engine: target.engine,
              doc: """
                The app's typography vocabulary. Chosen by hierarchy and context, \
                never by raw size — the sizes live in the palette, one file over.
                """,
              groups: config.fonts.map { (name: $0.name, tokens: $0.tokens.map { ($0.name, $0.doc) }) })),
    ]
    if !config.gradients.isEmpty {
      files.append(.init(
        path: "\(target.output)/SemanticGradient.swift",
        content: swiftVocabulary(
          enumName: "SemanticGradient", conformance: "GradientAssetable", engine: target.engine,
          doc: "The app's gradient vocabulary.",
          groups: [(name: nil, tokens: config.gradients.map { ($0.name, $0.doc) })])))
    }
    files.append(.init(path: "\(target.output)/\(target.theme)Palette.swift",
                       content: swiftPalette(config: config, target: target)))
    return files
  }

  private static func swiftVocabulary(
    enumName: String, conformance: String, engine: String, doc: String,
    groups: [(name: String?, tokens: [(String, String?)])]
  ) -> String {
    var out = header(generatedBanner)
    out += ["#if os(iOS)", "", "import \(engine)", ""]
    out += comment(doc, prefix: "/// ", indent: "")
    out.append("public enum \(enumName): \(conformance) {")
    for group in groups {
      if let name = group.name {
        out.append("")
        out.append("  // MARK: - \(name)")
        out.append("")
      }
      for (token, tokenDoc) in group.tokens {
        // A blank line only where one earns its keep: under a heading, and
        // around a documented case, so an undocumented run reads as one list.
        if let tokenDoc {
          out.append("")
          out += comment(tokenDoc, prefix: "/// ", indent: "  ")
        }
        out.append("  case \(token)")
      }
    }
    out += ["}", "", "#endif", ""]
    return render(out)
  }

  private static func swiftPalette(config: DesignTokenConfig, target: DesignTokenConfig.SwiftTarget) -> String {
    let theme = target.theme
    var out = header(generatedBanner)
    // SwiftUI enters only for the gradient table's `Gradient`/`Color`; a
    // config with no gradients gets no unused import.
    var imports = ["import UIKit"]
    if !config.gradients.isEmpty { imports.append("import SwiftUI") }
    imports.append("import \(target.engine)")
    out += ["#if os(iOS)", ""] + imports + [""]

    // Colours.
    out += comment("""
      The colour values, one entry per `SemanticColor`.

      The switch is exhaustive over the vocabulary, so a token added to the \
      config gets a value in the same generation — the property that makes the \
      vocabulary and the palette one unit rather than two lists kept aligned by \
      hand.
      """, prefix: "/// ", indent: "")
    out.append("extension \(theme) {")
    out.append("  public typealias _ColorAsset = SemanticColor")
    out.append("")
    out.append("  public func colorSet(for asset: _ColorAsset) -> ColorSet {")
    out.append("    switch asset {")
    for group in config.colors {
      if let name = group.name {
        out.append("")
        out.append("    // MARK: \(name)")
        out.append("")
      }
      for token in group.tokens {
        if let note = token.note {
          out.append("")
          out += comment(note, prefix: "// ", indent: "    ")
        }
        out.append("    case .\(token.name):")
        switch token.appearance {
        case let .auto(light, dark):
          // One line where it fits the 100-column soft limit both languages'
          // tables keep, wrapped where the alpha arguments push past it.
          let oneLine = "      return ColorSet(.auto(light: \(swiftColor(light)), dark: \(swiftColor(dark))))"
          if oneLine.count <= 100 {
            out.append(oneLine)
          } else {
            out.append("      return ColorSet(.auto(")
            out.append("        light: \(swiftColor(light)),")
            out.append("        dark: \(swiftColor(dark))))")
          }
        case let .fixed(value):
          out.append("      return ColorSet(.static(\(swiftColor(value))))")
        }
      }
    }
    out += ["    }", "  }", "}", ""]

    // Typography.
    out += comment("""
      One typography entry, in the terms both platforms read: a family, a \
      weight, a size, a line height, tracking as a fraction of the em, the \
      variable-font axes a cut is pinned at, and the Dynamic Type style it \
      scales against.

      The axes are load-bearing. A variable face addressed by weight alone \
      renders at its default optical size — no error, visibly wrong glyphs — so \
      the cut a token names is the family plus the axis values, and the app's \
      resolver reads both.
      """, prefix: "/// ", indent: "")
    out.append("extension \(theme) {")
    out.append("  public struct FontToken {")
    out.append("    public let family: FontFamilyToken")
    out.append("    public let weight: Int")
    out.append("    public let size: CGFloat")
    out.append("    public let lineHeight: CGFloat")
    out.append("    public let trackingEm: CGFloat")
    out.append("    public let opticalSize: CGFloat?")
    out.append("    public let softness: CGFloat?")
    out.append("    public let width: CGFloat?")
    out.append("    public let textStyle: UIFont.TextStyle")
    out.append("  }")
    out.append("")
    out += comment("""
      Which of the app's three faces a token is set in. The token names a \
      family, never a file: font resources are app-owned, and the app's \
      resolver turns a family and its axes into a registered face.
      """, prefix: "/// ", indent: "  ")
    out.append("  public enum FontFamilyToken {")
    for family in DesignTokenConfig.FontFamily.allCases { out.append("    case \(family.rawValue)") }
    out.append("  }")
    out.append("}")
    out.append("")
    out += comment("The type values, one entry per `SemanticFont`.", prefix: "/// ", indent: "")
    out.append("extension \(theme) {")
    out.append("  public typealias _FontAsset = SemanticFont")
    out.append("")
    out.append("  public func fontToken(for asset: _FontAsset) -> FontToken {")
    out.append("    switch asset {")
    for group in config.fonts {
      if let name = group.name {
        out.append("")
        out.append("    // MARK: \(name)")
        out.append("")
      }
      for token in group.tokens {
        out.append("")
        if let note = token.note { out += comment(note, prefix: "// ", indent: "    ") }
        out.append("    case .\(token.name):")
        out.append("      return FontToken(")
        out.append("        family: .\(token.family.rawValue),")
        out.append("        weight: \(token.weight),")
        out.append("        size: \(swiftNumber(token.size)),")
        out.append("        lineHeight: \(swiftNumber(token.lineHeight)),")
        out.append("        trackingEm: \(swiftNumber(token.tracking)),")
        out.append("        opticalSize: \(token.opticalSize.map(swiftNumber) ?? "nil"),")
        out.append("        softness: \(token.softness.map(swiftNumber) ?? "nil"),")
        out.append("        width: \(token.width.map(swiftNumber) ?? "nil"),")
        out.append("        textStyle: .\(token.textStyle ?? "body"))")
      }
    }
    out += ["    }", "  }", "}", ""]

    // Gradients.
    if !config.gradients.isEmpty {
      out += comment("The gradient values, one entry per `SemanticGradient`.",
                     prefix: "/// ", indent: "")
      out.append("extension \(theme) {")
      out.append("  public typealias _GradientAsset = SemanticGradient")
      out.append("")
      out.append("  public func gradientSet(for asset: _GradientAsset) -> GradientSet {")
      out.append("    switch asset {")
      for token in config.gradients {
        out.append("")
        if let note = token.note { out += comment(note, prefix: "// ", indent: "    ") }
        out.append("    case .\(token.name):")
        switch token.appearance {
        case .fixed(let stops):
          out.append("      return GradientSet(.static(Gradient(colors: [")
          out += stops.map { "        Color(uiColor: \(swiftColor($0)))," }
          out.append("      ])))")
        case .auto(let light, let dark):
          out.append("      return GradientSet(.auto(")
          out.append("        light: Gradient(colors: [")
          out += light.map { "          Color(uiColor: \(swiftColor($0)))," }
          out.append("        ]),")
          out.append("        dark: Gradient(colors: [")
          out += dark.map { "          Color(uiColor: \(swiftColor($0)))," }
          out.append("        ])))")
        }
      }
      out += ["    }", "  }", "}", ""]
    }

    out += comment("""
      The literal form the tables above are written in. File-private on \
      purpose: the generated file carries its own colour construction so it \
      needs nothing from the app, and an app-wide hex convenience stays the \
      app's to declare.
      """, prefix: "/// ", indent: "")
    out.append("private func tokenColor(_ rgb: UInt32, alpha: CGFloat = 1) -> UIColor {")
    out.append("  UIColor(")
    out.append("    red: CGFloat((rgb >> 16) & 0xff) / 255.0,")
    out.append("    green: CGFloat((rgb >> 8) & 0xff) / 255.0,")
    out.append("    blue: CGFloat(rgb & 0xff) / 255.0,")
    out.append("    alpha: alpha)")
    out.append("}")
    out += ["", "#endif", ""]
    return render(out)
  }

  private static func swiftColor(_ value: DesignTokenConfig.ColorValue) -> String {
    value.alpha == 1
      ? "tokenColor(\(hex6(value.rgb)))"
      : "tokenColor(\(hex6(value.rgb)), alpha: \(swiftNumber(value.alpha)))"
  }

  // MARK: - Kotlin

  static func emitKotlin(config: DesignTokenConfig, target: DesignTokenConfig.KotlinTarget)
    -> [GeneratedDesignTokenFile]
  {
    var files: [GeneratedDesignTokenFile] = [
      .init(path: "\(target.output)/SemanticColor.kt",
            content: kotlinVocabulary(
              enumName: "SemanticColor", target: target,
              doc: """
                The app's colour vocabulary — the one list, read by this tree and by \
                every other tree generated from the same config.

                Entry names are lowerCamel rather than Kotlin's usual UPPER_SNAKE for \
                enum entries: one spelling per token across both languages makes a \
                token grep once instead of twice.
                """,
              groups: config.colors.map { (name: $0.name, tokens: $0.tokens.map { ($0.name, $0.doc) }) })),
      .init(path: "\(target.output)/SemanticFont.kt",
            content: kotlinVocabulary(
              enumName: "SemanticFont", target: target,
              doc: """
                The app's typography vocabulary. Chosen by hierarchy and context, \
                never by raw size — the sizes live in the palette, one file over.

                Entry names carry the spelling given on `SemanticColor`.
                """,
              groups: config.fonts.map { (name: $0.name, tokens: $0.tokens.map { ($0.name, $0.doc) }) })),
    ]
    if !config.gradients.isEmpty {
      files.append(.init(
        path: "\(target.output)/SemanticGradient.kt",
        content: kotlinVocabulary(
          enumName: "SemanticGradient", target: target,
          doc: """
            The app's gradient vocabulary.

            Material carries no gradient slot — `ColorScheme` holds colours and \
            `Typography` type — so a Compose surface reads its stops from the palette \
            by token and paints them itself. The Apple tree reaches the same stops \
            through its theme, which does carry a gradient asset kind.
            """,
          groups: [(name: nil, tokens: config.gradients.map { ($0.name, $0.doc) })])))
    }
    files.append(.init(path: "\(target.output)/\(target.palette).kt",
                       content: kotlinPalette(config: config, target: target)))
    return files
  }

  private static func kotlinVocabulary(
    enumName: String, target: DesignTokenConfig.KotlinTarget, doc: String,
    groups: [(name: String?, tokens: [(String, String?)])]
  ) -> String {
    var out = header(generatedBanner)
    out += ["package \(target.package)", ""]
    out += kdoc(doc, indent: "")
    out.append("enum class \(enumName) {")
    for group in groups {
      if let name = group.name {
        out.append("")
        out.append("  // \(name)")
      }
      for (token, tokenDoc) in group.tokens {
        if let tokenDoc {
          out.append("")
          out += kdoc(tokenDoc, indent: "  ")
        }
        out.append("  \(token),")
      }
    }
    out += ["}", ""]
    return render(out)
  }

  private static func kotlinPalette(config: DesignTokenConfig, target: DesignTokenConfig.KotlinTarget) -> String {
    var out = header(generatedBanner)
    out += ["package \(target.package)", ""]
    var imports = ["import \(target.engine).ColorToken",
                   "import \(target.engine).FontFamilyToken",
                   "import \(target.engine).FontToken"]
    if !config.gradients.isEmpty { imports.append("import \(target.engine).GradientToken") }
    out += imports + [""]
    out += kdoc("""
      The values behind the vocabularies — one entry per token, in the terms \
      the engine reads.

      Colours and gradient stops are `0xAARRGGBB`. Each `when` is exhaustive \
      over its vocabulary, so a token added to the config gets a value in the \
      same generation.
      """, indent: "")
    out.append("object \(target.palette) {")
    out.append("")
    out.append("  fun color(token: SemanticColor): ColorToken =")
    out.append("    when (token) {")
    for group in config.colors {
      if let name = group.name {
        out.append("")
        out.append("      // \(name)")
      }
      for token in group.tokens {
        if let note = token.note { out += comment(note, prefix: "// ", indent: "      ") }
        let value: String
        switch token.appearance {
        case let .auto(light, dark):
          value = "ColorToken.auto(light = \(hex8(light.argb)), dark = \(hex8(dark.argb)))"
        case let .fixed(value_):
          value = "ColorToken.fixed(\(hex8(value_.argb)))"
        }
        let oneLine = "      SemanticColor.\(token.name) -> \(value)"
        if oneLine.count <= 100 {
          out.append(oneLine)
        } else {
          out.append("      SemanticColor.\(token.name) ->")
          out.append("        \(value)")
        }
      }
    }
    out.append("    }")
    out.append("")
    out.append("  fun font(token: SemanticFont): FontToken =")
    out.append("    when (token) {")
    for group in config.fonts {
      if let name = group.name {
        out.append("")
        out.append("      // \(name)")
      }
      for token in group.tokens {
        if let note = token.note { out += comment(note, prefix: "// ", indent: "      ") }
        out.append("      SemanticFont.\(token.name) ->")
        out.append("        FontToken(")
        out.append("          family = FontFamilyToken.\(token.family.kotlinEntry),")
        out.append("          weight = \(token.weight),")
        out.append("          sizeSp = \(kotlinNumber(token.size)),")
        out.append("          lineHeightSp = \(kotlinNumber(token.lineHeight)),")
        out.append("          trackingEm = \(kotlinNumber(token.tracking)),")
        out.append("          opticalSize = \(token.opticalSize.map(kotlinNumber) ?? "null"),")
        out.append("          softness = \(token.softness.map(kotlinNumber) ?? "null"),")
        out.append("          width = \(token.width.map(kotlinNumber) ?? "null"),")
        out.append("        )")
      }
    }
    out.append("    }")

    if !config.gradients.isEmpty {
      out.append("")
      out.append("  fun gradient(token: SemanticGradient): GradientToken =")
      out.append("    when (token) {")
      for token in config.gradients {
        out.append("")
        if let note = token.note { out += comment(note, prefix: "// ", indent: "      ") }
        out.append("      SemanticGradient.\(token.name) ->")
        switch token.appearance {
        case let .fixed(stops):
          out += kotlinStops(stops, opening: "        GradientToken.fixed(",
                             indent: "        ", trailing: ")")
        case let .auto(light, dark):
          out.append("        GradientToken.auto(")
          out += kotlinStops(light, opening: "          light = ",
                             indent: "          ", trailing: ",")
          out += kotlinStops(dark, opening: "          dark = ",
                             indent: "          ", trailing: ",")
          out.append("        )")
        }
      }
      out.append("    }")
    }

    out.append("}")
    out.append("")
    return render(out)
  }

  /// A stop list: `listOf(0xFF…, 0xFF…)` on one line where it fits the
  /// 100-column soft limit both languages' tables keep, one stop per line where
  /// it does not. `opening` is everything before `listOf(` on the first line,
  /// its indentation included.
  ///
  /// Every stop is opaque by the config grammar, so each literal is `0xFF……`
  /// — above `Int.MAX_VALUE`, which is what types the list `List<Long>` with no
  /// explicit type argument.
  private static func kotlinStops(
    _ stops: [DesignTokenConfig.ColorValue], opening: String, indent: String, trailing: String
  ) -> [String] {
    let values = stops.map { hex8($0.argb) }
    let oneLine = "\(opening)listOf(\(values.joined(separator: ", ")))\(trailing)"
    if oneLine.count <= 100 { return [oneLine] }
    var out = ["\(opening)listOf("]
    out += values.map { "\(indent)  \($0)," }
    out.append("\(indent))\(trailing)")
    return out
  }

  private static func kdoc(_ text: String, indent: String) -> [String] {
    var out = ["\(indent)/**"]
    out += comment(text, prefix: " * ", indent: indent)
    out.append("\(indent) */")
    return out
  }
}
