// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

import CanonicalSumGen
import XCTest

/// The codegen vehicle's golden receipt — one worst-case enum covering the whole
/// payload-rule matrix (no payload; single unlabeled; single unlabeled optional;
/// labeled mixed; labeled single-optional; labeled all-optional), its generated
/// file pinned BYTE-FOR-BYTE as a literal. This is one half of the two
/// vehicles' lockstep gate: any emission-rule change must consciously update
/// this golden AND the macro package's expansion pin in the same commit.
final class GoldenTests: XCTestCase {
  func testWorstCaseGenerationMatchesGolden() throws {
    let dir = FileManager.default.temporaryDirectory
      .appendingPathComponent("csg-golden-\(ProcessInfo.processInfo.processIdentifier)")
    try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: dir) }
    let source = dir.appendingPathComponent("WorstCaseFeature.swift")
    try Data(Self.worstCaseSource.utf8).write(to: source)

    let output = try XCTUnwrap(CanonicalSumGen.generate(fromSource: source))
    XCTAssertEqual(output.outputURL.lastPathComponent, "WorstCaseSerialization.generated.swift")
    XCTAssertEqual(output.enumCount, 1)
    if output.content != Self.golden {
      let dump = FileManager.default.temporaryDirectory
        .appendingPathComponent("canonical-sum-gen-actual.swift")
      try? Data(output.content.utf8).write(to: dump)
      print("GoldenTests: actual output dumped to \(dump.path)")
    }
    XCTAssertEqual(output.content, Self.golden, "generated coder file drifted from the golden")
  }

  func testSourceWithoutMarkerEnumsGeneratesNothing() throws {
    let dir = FileManager.default.temporaryDirectory
      .appendingPathComponent("csg-empty-\(ProcessInfo.processInfo.processIdentifier)")
    try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: dir) }
    let source = dir.appendingPathComponent("Plain.swift")
    // Mentions the marker only in a comment — the scan prefilter would hit it,
    // the parse must not.
    try Data("// not CanonicalSumCodable\nstruct Plain {}\n".utf8).write(to: source)
    XCTAssertNil(try CanonicalSumGen.generate(fromSource: source))
  }

  static let worstCaseSource = """
    import Foundation

    enum WorstCaseRoute: Equatable, CanonicalSumCodable {
      case home
      case detail(String)
      case peek(Int?)
      case search(query: String?, scope: Int)
      case badge(count: Int?)
      case filters(kind: String?, active: Bool?)
    }
    """

  static let golden = #"""
    // Copyright (c) 2026 Modaal.dev
    // Licensed under the MIT License. See LICENSE file for details.

    // GENERATED by `duet canonical-sum` from WorstCaseFeature.swift — do not edit.
    // Regenerate: `duet record` (regen is folded in) or `duet canonical-sum`;
    // drift-gated by `duet record --check`. Canonical `{"case": …}` coding per the
    // framework's serialization contract (contracts/serialization.md §4).

    import Foundation

    private enum SumCodingKeys: String, CodingKey {
      case caseName = "case"
      case value
    }

    private struct ValueKey: CodingKey {
      let stringValue: String
      var intValue: Int? { nil }
      init(_ key: String) { stringValue = key }
      init?(stringValue: String) { self.stringValue = stringValue }
      init?(intValue: Int) { nil }
    }

    extension WorstCaseRoute {
      public static let canonicalCodersGenerated = true

      public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: SumCodingKeys.self)
        switch try c.decode(String.self, forKey: .caseName) {
        case "home": self = .home
        case "detail":
          self = .detail(try c.decode(String.self, forKey: .value))
        case "peek":
          self = .peek(try c.decodeIfPresent(Int.self, forKey: .value))
        case "search":
          let v = try c.nestedContainer(keyedBy: ValueKey.self, forKey: .value)
          self = .search(
            query: try v.decodeIfPresent(String.self, forKey: ValueKey("query")),
            scope: try v.decode(Int.self, forKey: ValueKey("scope")))
        case "badge":
          if c.contains(.value) {
            let v = try c.nestedContainer(keyedBy: ValueKey.self, forKey: .value)
            self = .badge(
              count: try v.decodeIfPresent(Int.self, forKey: ValueKey("count")))
          } else {
            self = .badge(count: nil)
          }
        case "filters":
          if c.contains(.value) {
            let v = try c.nestedContainer(keyedBy: ValueKey.self, forKey: .value)
            self = .filters(
              kind: try v.decodeIfPresent(String.self, forKey: ValueKey("kind")),
              active: try v.decodeIfPresent(Bool.self, forKey: ValueKey("active")))
          } else {
            self = .filters(kind: nil, active: nil)
          }
        case let unknown:
          throw DecodingError.dataCorruptedError(
            forKey: .caseName, in: c,
            debugDescription: "Unknown WorstCaseRoute case '\(unknown)'")
        }
      }

      public func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: SumCodingKeys.self)
        switch self {
        case .home: try c.encode("home", forKey: .caseName)
        case let .detail(v0):
          try c.encode("detail", forKey: .caseName)
          try c.encode(v0, forKey: .value)
        case let .peek(v0):
          try c.encode("peek", forKey: .caseName)
          if let v0 { try c.encode(v0, forKey: .value) }
        case let .search(query, scope):
          try c.encode("search", forKey: .caseName)
          var v = c.nestedContainer(keyedBy: ValueKey.self, forKey: .value)
          try v.encodeIfPresent(query, forKey: ValueKey("query"))
          try v.encode(scope, forKey: ValueKey("scope"))
        case let .badge(count):
          try c.encode("badge", forKey: .caseName)
          if count != nil {
            var v = c.nestedContainer(keyedBy: ValueKey.self, forKey: .value)
            try v.encodeIfPresent(count, forKey: ValueKey("count"))
          }
        case let .filters(kind, active):
          try c.encode("filters", forKey: .caseName)
          if kind != nil || active != nil {
            var v = c.nestedContainer(keyedBy: ValueKey.self, forKey: .value)
            try v.encodeIfPresent(kind, forKey: ValueKey("kind"))
            try v.encodeIfPresent(active, forKey: ValueKey("active"))
          }
        }
      }
    }

    """#
}
