// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

package com.example.theming

import dev.modaal.duet.services.theming.ColorToken
import dev.modaal.duet.services.theming.FontFamilyToken
import dev.modaal.duet.services.theming.FontToken

/**
 * The values behind the vocabularies — one entry per token, in the terms the
 * engine reads.
 *
 * Colours are `0xAARRGGBB`. Each `when` is exhaustive over its vocabulary, so a
 * token added to the config gets a value in the same generation.
 */
object MainPalette {

  fun color(token: SemanticColor): ColorToken =
    when (token) {

      // Labels
      SemanticColor.labelPrimary -> ColorToken.auto(light = 0xFF1A1A1A, dark = 0xFFF2F2F2)
      SemanticColor.labelSecondary -> ColorToken.auto(light = 0xFF6B6B6B, dark = 0xFF9A9A9A)
      // The one label that is allowed to fail contrast — nothing is read from
      // it.
      SemanticColor.labelDisabled -> ColorToken.auto(light = 0xFFA8A8A8, dark = 0xFF565656)
      // Fixed on purpose: the fill it sits on does not invert.
      SemanticColor.labelOnAccent -> ColorToken.fixed(0xFFFFFFFF)

      // Surfaces
      // The page. Warm off-white rather than pure white.
      SemanticColor.surfacePrimary -> ColorToken.auto(light = 0xFFFBFAF7, dark = 0xFF141414)
      SemanticColor.surfaceRaised -> ColorToken.auto(light = 0xFFFFFFFF, dark = 0xFF1E1E1E)
      SemanticColor.surfaceScrim -> ColorToken.auto(light = 0x3D1A1A1A, dark = 0x80000000)

      // Separators and fills
      SemanticColor.separatorHairline -> ColorToken.auto(light = 0x421A1A1A, dark = 0x42F2F2F2)
      SemanticColor.fillPrimary -> ColorToken.auto(light = 0x141A1A1A, dark = 0x1FF2F2F2)
      // Black and white rather than the ink and paper tokens: a grid line reads
      // as a tint of the surface under it, whatever that surface is.
      SemanticColor.fillGrid -> ColorToken.auto(light = 0x0D000000, dark = 0x0AFFFFFF)

      // Interactive
      SemanticColor.interactivePrimary -> ColorToken.auto(light = 0xFF1A1A1A, dark = 0xFFF2F2F2)
      SemanticColor.interactivePrimaryPressed ->
        ColorToken.auto(light = 0xD91A1A1A, dark = 0xD9F2F2F2)
      // 0.3 × 255 is 76.5 — the one alpha in this palette that lands exactly
      // between two bytes, and the byte the Kotlin table carries is 0x4D.
      SemanticColor.interactiveDisabledLabel ->
        ColorToken.auto(light = 0x4D1A1A1A, dark = 0x4DF2F2F2)
      SemanticColor.interactiveSelected -> ColorToken.auto(light = 0x1F3D2E5C, dark = 0x299A82C4)

      // Feedback
      SemanticColor.feedbackSuccess -> ColorToken.auto(light = 0xFF3F7A46, dark = 0xFF7FBE86)
      SemanticColor.feedbackSuccessSurface -> ColorToken.auto(light = 0x1A3F7A46, dark = 0x247FBE86)
      SemanticColor.feedbackError -> ColorToken.auto(light = 0xFFB3261E, dark = 0xFFE7796F)
      SemanticColor.feedbackErrorSurface -> ColorToken.auto(light = 0x1AB3261E, dark = 0x24E7796F)
      SemanticColor.accent -> ColorToken.auto(light = 0xFF3D2E5C, dark = 0xFF9A82C4)
      SemanticColor.shadowAmbient -> ColorToken.fixed(0x29000000)
    }

  fun font(token: SemanticFont): FontToken =
    when (token) {

      // Display — the serif face
      // Large `opsz` and high `SOFT` — the display cut, not the body cut scaled
      // up.
      SemanticFont.largeTitle ->
        FontToken(
          family = FontFamilyToken.Serif,
          weight = 400,
          sizeSp = 34.0,
          lineHeightSp = 41.0,
          trackingEm = -0.01,
          opticalSize = 144.0,
          softness = 50.0,
          width = null,
        )
      SemanticFont.title2 ->
        FontToken(
          family = FontFamilyToken.Serif,
          weight = 500,
          sizeSp = 22.0,
          lineHeightSp = 28.0,
          trackingEm = 0.0,
          opticalSize = 48.0,
          softness = 30.0,
          width = null,
        )

      // Body — the serif face at reading sizes
      // `opsz` tracks the point size here rather than the display sizes above.
      SemanticFont.bodyRegular ->
        FontToken(
          family = FontFamilyToken.Serif,
          weight = 400,
          sizeSp = 17.0,
          lineHeightSp = 26.0,
          trackingEm = 0.0,
          opticalSize = 17.0,
          softness = 20.0,
          width = null,
        )
      SemanticFont.bodyEmphasized ->
        FontToken(
          family = FontFamilyToken.Serif,
          weight = 600,
          sizeSp = 17.0,
          lineHeightSp = 26.0,
          trackingEm = 0.0,
          opticalSize = 17.0,
          softness = 20.0,
          width = null,
        )

      // Chrome — the sans face
      SemanticFont.headline ->
        FontToken(
          family = FontFamilyToken.Sans,
          weight = 600,
          sizeSp = 17.0,
          lineHeightSp = 22.0,
          trackingEm = 0.0,
          opticalSize = null,
          softness = null,
          width = 100.0,
        )
      SemanticFont.subheadRegular ->
        FontToken(
          family = FontFamilyToken.Sans,
          weight = 400,
          sizeSp = 15.0,
          lineHeightSp = 20.0,
          trackingEm = 0.0,
          opticalSize = null,
          softness = null,
          width = 100.0,
        )

      // Labels — the mono face
      // Every mono label carries 0.08 em of tracking; the face is set in
      // ALLCAPS at these sizes and reads tight without it.
      SemanticFont.footnoteRegular ->
        FontToken(
          family = FontFamilyToken.Mono,
          weight = 400,
          sizeSp = 13.0,
          lineHeightSp = 17.0,
          trackingEm = 0.08,
          opticalSize = null,
          softness = null,
          width = null,
        )
      // The same 13/17 metrics as `footnoteRegular` — medium is a weight step,
      // not a size step, so a regular-to-medium swap must not resize the text.
      SemanticFont.footnoteMedium ->
        FontToken(
          family = FontFamilyToken.Mono,
          weight = 500,
          sizeSp = 13.0,
          lineHeightSp = 17.0,
          trackingEm = 0.08,
          opticalSize = null,
          softness = null,
          width = null,
        )
      SemanticFont.captionRegular ->
        FontToken(
          family = FontFamilyToken.Mono,
          weight = 400,
          sizeSp = 11.0,
          lineHeightSp = 14.0,
          trackingEm = 0.08,
          opticalSize = null,
          softness = null,
          width = null,
        )
    }
}
