// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

#if os(iOS)

import UIKit
import SwiftUI
import DuetTheming

/// The colour values, one entry per `SemanticColor`.
///
/// The switch is exhaustive over the vocabulary, so a token added to the config
/// gets a value in the same generation — the property that makes the vocabulary
/// and the palette one unit rather than two lists kept aligned by hand.
extension MainTheme {
  public typealias _ColorAsset = SemanticColor

  public func colorSet(for asset: _ColorAsset) -> ColorSet {
    switch asset {

    // MARK: Labels

    case .labelPrimary:
      return ColorSet(.auto(light: tokenColor(0x1A1A1A), dark: tokenColor(0xF2F2F2)))
    case .labelSecondary:
      return ColorSet(.auto(light: tokenColor(0x6B6B6B), dark: tokenColor(0x9A9A9A)))

    // The one label that is allowed to fail contrast — nothing is read from it.
    case .labelDisabled:
      return ColorSet(.auto(light: tokenColor(0xA8A8A8), dark: tokenColor(0x565656)))

    // Fixed on purpose: the fill it sits on does not invert.
    case .labelOnAccent:
      return ColorSet(.static(tokenColor(0xFFFFFF)))

    // MARK: Surfaces

    // The page. Warm off-white rather than pure white.
    case .surfacePrimary:
      return ColorSet(.auto(light: tokenColor(0xFBFAF7), dark: tokenColor(0x141414)))
    case .surfaceRaised:
      return ColorSet(.auto(light: tokenColor(0xFFFFFF), dark: tokenColor(0x1E1E1E)))
    case .surfaceScrim:
      return ColorSet(.auto(
        light: tokenColor(0x1A1A1A, alpha: 0.24),
        dark: tokenColor(0x000000, alpha: 0.5)))

    // MARK: Separators and fills

    case .separatorHairline:
      return ColorSet(.auto(
        light: tokenColor(0x1A1A1A, alpha: 0.26),
        dark: tokenColor(0xF2F2F2, alpha: 0.26)))
    case .fillPrimary:
      return ColorSet(.auto(
        light: tokenColor(0x1A1A1A, alpha: 0.08),
        dark: tokenColor(0xF2F2F2, alpha: 0.12)))

    // Black and white rather than the ink and paper tokens: a grid line reads
    // as a tint of the surface under it, whatever that surface is.
    case .fillGrid:
      return ColorSet(.auto(
        light: tokenColor(0x000000, alpha: 0.05),
        dark: tokenColor(0xFFFFFF, alpha: 0.04)))

    // MARK: Interactive

    case .interactivePrimary:
      return ColorSet(.auto(light: tokenColor(0x1A1A1A), dark: tokenColor(0xF2F2F2)))
    case .interactivePrimaryPressed:
      return ColorSet(.auto(
        light: tokenColor(0x1A1A1A, alpha: 0.85),
        dark: tokenColor(0xF2F2F2, alpha: 0.85)))

    // 0.3 × 255 is 76.5 — the one alpha in this palette that lands exactly
    // between two bytes, and the byte the Kotlin table carries is 0x4D.
    case .interactiveDisabledLabel:
      return ColorSet(.auto(
        light: tokenColor(0x1A1A1A, alpha: 0.3),
        dark: tokenColor(0xF2F2F2, alpha: 0.3)))
    case .interactiveSelected:
      return ColorSet(.auto(
        light: tokenColor(0x3D2E5C, alpha: 0.12),
        dark: tokenColor(0x9A82C4, alpha: 0.16)))

    // MARK: Feedback

    case .feedbackSuccess:
      return ColorSet(.auto(light: tokenColor(0x3F7A46), dark: tokenColor(0x7FBE86)))
    case .feedbackSuccessSurface:
      return ColorSet(.auto(
        light: tokenColor(0x3F7A46, alpha: 0.1),
        dark: tokenColor(0x7FBE86, alpha: 0.14)))
    case .feedbackError:
      return ColorSet(.auto(light: tokenColor(0xB3261E), dark: tokenColor(0xE7796F)))
    case .feedbackErrorSurface:
      return ColorSet(.auto(
        light: tokenColor(0xB3261E, alpha: 0.1),
        dark: tokenColor(0xE7796F, alpha: 0.14)))
    case .accent:
      return ColorSet(.auto(light: tokenColor(0x3D2E5C), dark: tokenColor(0x9A82C4)))
    case .shadowAmbient:
      return ColorSet(.static(tokenColor(0x000000, alpha: 0.16)))
    }
  }
}

/// One typography entry, in the terms both platforms read: a family, a weight,
/// a size, a line height, tracking as a fraction of the em, the variable-font
/// axes a cut is pinned at, and the Dynamic Type style it scales against.
///
/// The axes are load-bearing. A variable face addressed by weight alone renders
/// at its default optical size — no error, visibly wrong glyphs — so the cut a
/// token names is the family plus the axis values, and the app's resolver reads
/// both.
extension MainTheme {
  public struct FontToken {
    public let family: FontFamilyToken
    public let weight: Int
    public let size: CGFloat
    public let lineHeight: CGFloat
    public let trackingEm: CGFloat
    public let opticalSize: CGFloat?
    public let softness: CGFloat?
    public let width: CGFloat?
    public let textStyle: UIFont.TextStyle
  }

  /// Which of the app's three faces a token is set in. The token names a
  /// family, never a file: font resources are app-owned, and the app's resolver
  /// turns a family and its axes into a registered face.
  public enum FontFamilyToken {
    case serif
    case sans
    case mono
  }
}

/// The type values, one entry per `SemanticFont`.
extension MainTheme {
  public typealias _FontAsset = SemanticFont

  public func fontToken(for asset: _FontAsset) -> FontToken {
    switch asset {

    // MARK: Display — the serif face

    // Large `opsz` and high `SOFT` — the display cut, not the body cut scaled
    // up.
    case .largeTitle:
      return FontToken(
        family: .serif,
        weight: 400,
        size: 34,
        lineHeight: 41,
        trackingEm: -0.01,
        opticalSize: 144,
        softness: 50,
        width: nil,
        textStyle: .largeTitle)

    case .title2:
      return FontToken(
        family: .serif,
        weight: 500,
        size: 22,
        lineHeight: 28,
        trackingEm: 0,
        opticalSize: 48,
        softness: 30,
        width: nil,
        textStyle: .title2)

    // MARK: Body — the serif face at reading sizes

    // `opsz` tracks the point size here rather than the display sizes above.
    case .bodyRegular:
      return FontToken(
        family: .serif,
        weight: 400,
        size: 17,
        lineHeight: 26,
        trackingEm: 0,
        opticalSize: 17,
        softness: 20,
        width: nil,
        textStyle: .body)

    case .bodyEmphasized:
      return FontToken(
        family: .serif,
        weight: 600,
        size: 17,
        lineHeight: 26,
        trackingEm: 0,
        opticalSize: 17,
        softness: 20,
        width: nil,
        textStyle: .body)

    // MARK: Chrome — the sans face

    case .headline:
      return FontToken(
        family: .sans,
        weight: 600,
        size: 17,
        lineHeight: 22,
        trackingEm: 0,
        opticalSize: nil,
        softness: nil,
        width: 100,
        textStyle: .headline)

    case .subheadRegular:
      return FontToken(
        family: .sans,
        weight: 400,
        size: 15,
        lineHeight: 20,
        trackingEm: 0,
        opticalSize: nil,
        softness: nil,
        width: 100,
        textStyle: .subheadline)

    // MARK: Labels — the mono face

    // Every mono label carries 0.08 em of tracking; the face is set in ALLCAPS
    // at these sizes and reads tight without it.
    case .footnoteRegular:
      return FontToken(
        family: .mono,
        weight: 400,
        size: 13,
        lineHeight: 17,
        trackingEm: 0.08,
        opticalSize: nil,
        softness: nil,
        width: nil,
        textStyle: .footnote)

    // The same 13/17 metrics as `footnoteRegular` — medium is a weight step,
    // not a size step, so a regular-to-medium swap must not resize the text.
    case .footnoteMedium:
      return FontToken(
        family: .mono,
        weight: 500,
        size: 13,
        lineHeight: 17,
        trackingEm: 0.08,
        opticalSize: nil,
        softness: nil,
        width: nil,
        textStyle: .footnote)

    case .captionRegular:
      return FontToken(
        family: .mono,
        weight: 400,
        size: 11,
        lineHeight: 14,
        trackingEm: 0.08,
        opticalSize: nil,
        softness: nil,
        width: nil,
        textStyle: .caption1)
    }
  }
}

/// The gradient values, one entry per `SemanticGradient`.
extension MainTheme {
  public typealias _GradientAsset = SemanticGradient

  public func gradientSet(for asset: _GradientAsset) -> GradientSet {
    switch asset {

    // Both stops are the raised surface at different alphas, so the wash reads
    // as a fade rather than as a second colour.
    case .surfaceWash:
      return GradientSet(.static(Gradient(colors: [
        Color(uiColor: tokenColor(0xFFFFFF)),
        Color(uiColor: tokenColor(0xFBFAF7)),
      ])))

    // The two-appearance form: each appearance runs down its own surface ramp,
    // so the wash inverts with the page instead of staying a light wash on a
    // dark ground.
    case .surfaceHero:
      return GradientSet(.auto(
        light: Gradient(colors: [
          Color(uiColor: tokenColor(0xFBFAF7)),
          Color(uiColor: tokenColor(0xFFFFFF)),
        ]),
        dark: Gradient(colors: [
          Color(uiColor: tokenColor(0x141414)),
          Color(uiColor: tokenColor(0x1E1E1E)),
        ])))
    }
  }
}

/// The literal form the tables above are written in. File-private on purpose:
/// the generated file carries its own colour construction so it needs nothing
/// from the app, and an app-wide hex convenience stays the app's to declare.
private func tokenColor(_ rgb: UInt32, alpha: CGFloat = 1) -> UIColor {
  UIColor(
    red: CGFloat((rgb >> 16) & 0xff) / 255.0,
    green: CGFloat((rgb >> 8) & 0xff) / 255.0,
    blue: CGFloat(rgb & 0xff) / 255.0,
    alpha: alpha)
}

#endif
