// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

package com.example.theming

/**
 * The app's gradient vocabulary.
 *
 * Material carries no gradient slot — `ColorScheme` holds colours and
 * `Typography` type — so a Compose surface reads its stops from the palette by
 * token and paints them itself. The Apple tree reaches the same stops through
 * its theme, which does carry a gradient asset kind.
 */
enum class SemanticGradient {

  /**
   * The one gradient the design system keeps.
   */
  surfaceWash,

  /**
   * The wash behind a hero header.
   */
  surfaceHero,
}
