// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

package com.example.theming

/**
 * The app's colour vocabulary — the one list, read by this tree and by every
 * other tree generated from the same config.
 *
 * Entry names are lowerCamel rather than Kotlin's usual UPPER_SNAKE for enum
 * entries: one spelling per token across both languages makes a token grep once
 * instead of twice.
 */
enum class SemanticColor {

  // Labels
  labelPrimary,

  /**
   * Supporting text one step below the primary label: subtitles, helper text,
   * and secondary values that still have to read easily.
   *
   * Not a caption tier — the caption tokens are smaller and quieter, and
   * swapping one for the other changes the hierarchy rather than the weight.
   */
  labelSecondary,
  labelDisabled,

  /**
   * Label over an accent fill, in both appearances.
   */
  labelOnAccent,

  // Surfaces
  surfacePrimary,
  surfaceRaised,

  /**
   * Modal scrim — flat, no blur.
   */
  surfaceScrim,

  // Separators and fills
  separatorHairline,
  fillPrimary,
  fillGrid,

  // Interactive
  interactivePrimary,
  interactivePrimaryPressed,
  interactiveDisabledLabel,
  interactiveSelected,

  // Feedback
  feedbackSuccess,
  feedbackSuccessSurface,
  feedbackError,
  feedbackErrorSurface,

  /**
   * Accent — indicators and active hairlines. Never a fill.
   */
  accent,
  shadowAmbient,
}
