// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

#if os(iOS)

import DuetTheming

/// The app's typography vocabulary. Chosen by hierarchy and context, never by
/// raw size — the sizes live in the palette, one file over.
public enum SemanticFont: FontAssetable {

  // MARK: - Display — the serif face

  /// The largest title on a screen: top-level navigation titles, onboarding and
  /// hero surfaces.
  case largeTitle

  /// Section heading inside a screen.
  case title2

  // MARK: - Body — the serif face at reading sizes

  /// Default body text — paragraphs, list rows, descriptions.
  case bodyRegular
  case bodyEmphasized

  // MARK: - Chrome — the sans face

  /// Inline title for collapsed navigation bars, key values, and card titles. A
  /// UI title, not a content heading.
  case headline
  case subheadRegular

  // MARK: - Labels — the mono face

  /// Metadata, timestamps, and quiet supporting information.
  case footnoteRegular
  case footnoteMedium
  case captionRegular
}

#endif
