// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

package com.example.theming

/**
 * The app's gradient vocabulary.
 *
 * The engine fills no gradient role — Compose paints brushes at call sites, not
 * through a theme slot — so the vocabulary carries the names and the stops live
 * in the Apple table.
 */
enum class SemanticGradient {

  /**
   * The one gradient the design system keeps.
   */
  surfaceWash,
}
