// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

#if os(iOS)

import DuetTheming

/// The app's gradient vocabulary.
public enum SemanticGradient: GradientAssetable {

  /// The one gradient the design system keeps.
  case surfaceWash

  /// The wash behind a hero header.
  case surfaceHero
}

#endif
