// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

// GENERATED by `duet design-tokens` from parity/design-tokens.yaml —
// do not edit. Change a value in the config and regenerate:
// `duet design-tokens`. A hand-edit here fails `duet design-tokens --check`,
// which regenerates in memory and compares.

#if os(iOS)

import DuetTheming

/// The app's colour vocabulary — the one list, read by this tree and by every
/// other tree generated from the same config.
///
/// A token is chosen by what it means, never by what it looks like: the value
/// behind it is the config's to change.
public enum SemanticColor: ColorAssetable {

  // MARK: - Labels

  case labelPrimary

  /// Supporting text one step below the primary label: subtitles, helper text,
  /// and secondary values that still have to read easily.
  ///
  /// Not a caption tier — the caption tokens are smaller and quieter, and
  /// swapping one for the other changes the hierarchy rather than the weight.
  case labelSecondary
  case labelDisabled

  /// Label over an accent fill, in both appearances.
  case labelOnAccent

  // MARK: - Surfaces

  case surfacePrimary
  case surfaceRaised

  /// Modal scrim — flat, no blur.
  case surfaceScrim

  // MARK: - Separators and fills

  case separatorHairline
  case fillPrimary
  case fillGrid

  // MARK: - Interactive

  case interactivePrimary
  case interactivePrimaryPressed
  case interactiveDisabledLabel
  case interactiveSelected

  // MARK: - Feedback

  case feedbackSuccess
  case feedbackSuccessSurface
  case feedbackError
  case feedbackErrorSurface

  /// Accent — indicators and active hairlines. Never a fill.
  case accent
  case shadowAmbient
}

#endif
